REM Path to the SB scripts
SET SB_SCRIPT_PATH=F:\Projects\libs\libs_vstudio15

REM Get paths and variables
CALL %SB_SCRIPT_PATH%\set_paths.bat
CALL %SB_SCRIPT_PATH%\set_vars.bat

REM Set Visual Studio environment
CALL %SB_VSTUDIO_PATH%\vcvarsall.bat %SB_VSTUDIO_ARCHITECTURE%

REM Set path
SET PATH=%PATH%;%SB_CMAKE_PATH%

REM Convert paths to cmake (backslashes to forward slashes)
SET "SB_INSTALL_PATH_FWD=%SB_INSTALL_PATH:\=/%"

REM Boost
SET BOOST_ROOT=%SB_INSTALL_PATH_FWD%

REM OpenSSL
SET OPENSSL_ROOT_DIR=%SB_INSTALL_PATH_FWD%
REM SET OPENSSL_LIBRARIES="$LIBSDIR/lib/libcrypto.a;$LIBSDIR/lib/libssl.a"

REM wxWidgets
SET wxWidgets_ROOT_DIR=%SB_INSTALL_PATH_FWD%

REM Google Test
SET GOOGLE_TEST_ROOT=%SB_BUILD_PATH%
SET GOOGLE_TEST_INCLUDE=%SB_INSTALL_PATH_FWD%/include
SET GOOGLE_TEST_LIBRARY=optimized;%SB_BUILD_PATH%/gtest_rel/gtest.lib;debug;%SB_BUILD_PATH%/gtest_deb/gtest.lib

REM PFM
SET PFM_ROOT=F:\Projects\encfsMP\pfm_include

REM ENCFSMP_ADDITIONAL_LINK_LIBRARIES
SET ENCFSMP_ADDITIONAL_LINK_LIBRARIES=%SB_INSTALL_PATH_FWD%/lib/libpng16_static.lib;%SB_INSTALL_PATH_FWD%/lib/libjpeg.lib;%SB_INSTALL_PATH_FWD%/lib/tiff.lib;%SB_INSTALL_PATH_FWD%/lib/zlibstatic.lib
mkdir build_x64_sb
cd build_x64_sb
cmake -Wno-dev -G "Visual Studio 14 2015" -DCMAKE_CONFIGURATION_TYPES=Release;RelWithDebInfo;Debug -DCMAKE_GENERATOR_PLATFORM="x64" -DPFM_ROOT=%PFM_ROOT% -DCMAKE_PREFIX_PATH=%SB_INSTALL_PATH_FWD% -DwxWidgets_ROOT_DIR=%wxWidgets_ROOT_DIR% -DOPENSSL_ROOT_DIR=%OPENSSL_ROOT_DIR% -DGOOGLE_TEST_INCLUDE=%GOOGLE_TEST_INCLUDE% -DGOOGLE_TEST_LIBRARY=%GOOGLE_TEST_LIBRARY% -DENCFSMP_ADDITIONAL_LINK_LIBRARIES=%ENCFSMP_ADDITIONAL_LINK_LIBRARIES% ..\src

cd ..
pause
